# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/hi6210sft/setup-makefiles.sh

# Audio
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/hw/audio.primary.hi6210sft.so:system/lib/hw/audio.primary.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/audio.primary.hi6210sft.so:system/lib64/hw/audio.primary.hi6210sft.so \

# Binaries
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/bin/,system/bin) \

# Bluetooth
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/etc/bluetooth/bt_vendor.conf:system/etc/bluetooth/bt_vendor.conf

# DHCPCD
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf

# GNNS
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/etc/gnss,system/etc/gnss) \
    vendor/huawei/hi6210sft/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/huawei/hi6210sft/proprietary/etc/gpsconfig.xml:system/etc/gpsconfig.xml \
    vendor/huawei/hi6210sft/proprietary/etc/hisi_cfg.ini:system/etc/hisi_cfg.ini \
    vendor/huawei/hi6210sft/proprietary/etc/hisi_cfg_alice.ini:system/etc/hisi_cfg_alice.ini \
    vendor/huawei/hi6210sft/proprietary/etc/hisi_cfg_cherry.ini:system/etc/hisi_cfg_cherry.ini

# GPS
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/hw/gps.hi110x.default.so:system/lib/hw/gps.hi110x.default.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gps.hi110x.default.so:system/lib64/hw/gps.hi110x.default.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gps.hi6210sft.so:system/lib64/hw/gps.hi6210sft.so

# Graphics
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/huawei/hi6210sft/proprietary/lib/hw/gralloc.hi6210sft.so:system/lib/hw/gralloc.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/huawei/hi6210sft/proprietary/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gralloc.hi6210sft.so:system/lib64/hw/gralloc.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libion.so:system/lib64/libion.so

# Wifi ETC
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/etc/wifi/,system/etc/wifi) \

# 32 Bit Libs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/lib/,system/lib) \

# 64 Bit Libs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/lib64/,system/lib64) \

# Vendor 32 Bit Libs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/vendor/firmware,system/vendor/firmware) \
    vendor/huawei/hi6210sft/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/huawei/hi6210sft/proprietary/vendor/lib/libbt-vendor-hi110x.so:system/vendor/lib/libbt-vendor-hi110x.so \
    vendor/huawei/hi6210sft/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/huawei/hi6210sft/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so

# Vendor 64 Bit Libs
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/vendor/lib64/libbt-vendor-hi110x.so:system/vendor/lib64/libbt-vendor-hi110x.so

# XBIN
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/xbin/,system/xbin) \
