# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/hi6210sft/setup-makefiles.sh

# Bluetooth
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/etc/bluetooth/bt_vendor.conf:system/etc/bluetooth/bt_vendor.conf

# DHCPCD
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf

# GNNS
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/etc/gnss,system/etc/gnss) \
    vendor/huawei/hi6210sft/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/huawei/hi6210sft/proprietary/etc/gpsconfig.xml:system/etc/gpsconfig.xml \
    vendor/huawei/hi6210sft/proprietary/etc/hisi_cfg.ini:system/etc/hisi_cfg.ini \
    vendor/huawei/hi6210sft/proprietary/etc/hisi_cfg_alice.ini:system/etc/hisi_cfg_alice.ini \
    vendor/huawei/hi6210sft/proprietary/etc/hisi_cfg_cherry.ini:system/etc/hisi_cfg_cherry.ini

# GPS
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/hw/gps.hi110x.default.so:system/lib/hw/gps.hi110x.default.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gps.hi110x.default.so:system/lib64/hw/gps.hi110x.default.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gps.hi6210sft.so:system/lib64/hw/gps.hi6210sft.so

# Graphics
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/huawei/hi6210sft/proprietary/lib/hw/gralloc.hi6210sft.so:system/lib/hw/gralloc.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/huawei/hi6210sft/proprietary/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gralloc.hi6210sft.so:system/lib64/hw/gralloc.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libion.so:system/lib64/libion.so

# Wifi Binaries
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/bin/agnsscontrol:system/bin/agnsscontrol \
    vendor/huawei/hi6210sft/proprietary/bin/agnsslog:system/bin/agnsslog \
    vendor/huawei/hi6210sft/proprietary/bin/akmd09911:system/bin/akmd09911 \
    vendor/huawei/hi6210sft/proprietary/bin/check_root:system/bin/check_root \
    vendor/huawei/hi6210sft/proprietary/bin/device_monitor:system/bin/device_monitor \
    vendor/huawei/hi6210sft/proprietary/bin/hisi_connectivity.sh:system/bin/hisi_connectivity.sh \
    vendor/huawei/hi6210sft/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/huawei/hi6210sft/proprietary/bin/hostapd_cli_hisi:system/bin/hostapd_cli_hisi \
    vendor/huawei/hi6210sft/proprietary/bin/hostapd_hisi:system/bin/hostapd_hisi \
    vendor/huawei/hi6210sft/proprietary/bin/huawei_tp_test:system/bin/huawei_tp_test \
    vendor/huawei/hi6210sft/proprietary/bin/hwnff:system/bin/hwnff \
    vendor/huawei/hi6210sft/proprietary/bin/hwnffserver:system/bin/hwnffserver \
    vendor/huawei/hi6210sft/proprietary/bin/hwpged:system/bin/hwpged \
    vendor/huawei/hi6210sft/proprietary/bin/hw_ueventd:system/bin/hw_ueventd \
    vendor/huawei/hi6210sft/proprietary/bin/kmsgcat:system/bin/kmsgcat \
    vendor/huawei/hi6210sft/proprietary/bin/logctl_service:system/bin/logctl_service \
    vendor/huawei/hi6210sft/proprietary/bin/mac_addr_normalization:system/bin/mac_addr_normalization \
    vendor/huawei/hi6210sft/proprietary/bin/oam_app:system/bin/oam_app \
    vendor/huawei/hi6210sft/proprietary/bin/octty:system/bin/octty \
    vendor/huawei/hi6210sft/proprietary/bin/oeminfo_nvm_server:system/bin/oeminfo_nvm_server \
    vendor/huawei/hi6210sft/proprietary/bin/teecd:system/bin/teecd \
    vendor/huawei/hi6210sft/proprietary/bin/wl:system/bin/wl \
    vendor/huawei/hi6210sft/proprietary/bin/wl_config:system/bin/wl_config \
    vendor/huawei/hi6210sft/proprietary/bin/wpa_cli_hisi:system/bin/wpa_cli_hisi \
    vendor/huawei/hi6210sft/proprietary/bin/wpa_supplicant_hisi:system/bin/wpa_supplicant_hisi \

# Wifi ETC
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/etc/wifi/hostapd_hisi.conf:system/etc/wifi/hostapd_hisi.conf \
    vendor/huawei/hi6210sft/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/huawei/hi6210sft/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/huawei/hi6210sft/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \

# Wifi Libs
PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/hw/keystore.hi6210sft.so:system/lib/hw/keystore.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib/hw/memtrack.hi6210sft.so:system/lib/hw/memtrack.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib/hw/sensors.hi6210sft.so:system/lib/hw/sensors.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib/libagnssal.so:system/lib/libagnssal.so \
    vendor/huawei/hi6210sft/proprietary/lib/libbt_factory_test.so:system/lib/libbt_factory_test.so \
    vendor/huawei/hi6210sft/proprietary/lib/libbt_factory_test_hi110x.so:system/lib/libbt_factory_test_hi110x.so \
    vendor/huawei/hi6210sft/proprietary/lib/libgnssadapter.so:system/lib/libgnssadapter.so \
    vendor/huawei/hi6210sft/proprietary/lib/libteec.so:system/lib/libteec.so \
    vendor/huawei/hi6210sft/proprietary/lib/libwifi_factory_test.so:system/lib/libwifi_factory_test.so \
    vendor/huawei/hi6210sft/proprietary/lib/libwifi_factory_test_hi110x.so:system/lib/libwifi_factory_test_hi110x.so \
    vendor/huawei/hi6210sft/proprietary/lib/libwifipro.so:system/lib/libwifipro.so \
    vendor/huawei/hi6210sft/proprietary/lib/libwpa_client_hisi.so:system/lib/libwpa_client_hisi.so \
    vendor/huawei/hi6210sft/proprietary/lib/oamdrv.ko:system/lib/oamdrv.ko \
    vendor/huawei/hi6210sft/proprietary/lib/wifi.ko:system/lib/wifi.ko \

PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/keystore.hi6210sft.so:system/lib64/hw/keystore.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/memtrack.hi6210sft.so:system/lib64/hw/memtrack.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/sensors.hi6210sft.so:system/lib64/hw/sensors.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libagnssal.so:system/lib64/libagnssal.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libbt_factory_test.so:system/lib64/libbt_factory_test.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libbt_factory_test_hi110x.so:system/lib64/libbt_factory_test_hi110x.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libgnssadapter.so:system/lib64/libgnssadapter.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libteec.so:system/lib64/libteec.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libwifi_factory_test.so:system/lib64/libwifi_factory_test.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libwifi_factory_test_hi110x.so:system/lib64/libwifi_factory_test_hi110x.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libwifipro.so:system/lib64/libwifipro.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libwpa_client_hisi.so:system/lib64/libwpa_client_hisi.so \

PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/huawei/hi6210sft/proprietary/vendor/firmware/,system/vendor/firmware)

PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/huawei/hi6210sft/proprietary/vendor/lib/libbt-vendor-hi110x.so:system/vendor/lib/libbt-vendor-hi110x.so \
    vendor/huawei/hi6210sft/proprietary/vendor/lib64/libbt-vendor-hi110x.so:system/vendor/lib64/libbt-vendor-hi110x.so \
