# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/hi6210sft/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/hi6210sft/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/huawei/hi6210sft/proprietary/lib/hw/gralloc.hi6210sft.so:system/lib/hw/gralloc.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/huawei/hi6210sft/proprietary/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so \
    vendor/huawei/hi6210sft/proprietary/lib64/hw/gralloc.hi6210sft.so:system/lib64/hw/gralloc.hi6210sft.so \
    vendor/huawei/hi6210sft/proprietary/lib64/libion.so:system/lib64/libion.so
